// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARp1yTKZifJ8bgjMaRdRvZuW4gKWLlK4c',
    appId: '1:1081809524013:web:43d8ece652b4b10e6dafa4',
    messagingSenderId: '1081809524013',
    projectId: 'career-quest-a8c11',
    authDomain: 'career-quest-a8c11.firebaseapp.com',
    storageBucket: 'career-quest-a8c11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHuy5S-uOasFmkgu4PSmlIcpL1PuCENMg',
    appId: '1:1081809524013:android:13b1e0c9a9f677d76dafa4',
    messagingSenderId: '1081809524013',
    projectId: 'career-quest-a8c11',
    storageBucket: 'career-quest-a8c11.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARp1yTKZifJ8bgjMaRdRvZuW4gKWLlK4c',
    appId: '1:1081809524013:web:709c21fcd78f0c616dafa4',
    messagingSenderId: '1081809524013',
    projectId: 'career-quest-a8c11',
    authDomain: 'career-quest-a8c11.firebaseapp.com',
    storageBucket: 'career-quest-a8c11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvIMwIeIlSuRRUJO5DVnonEYjFU3snaVM',
    appId: '1:1081809524013:ios:c0acbbeae7d03b386dafa4',
    messagingSenderId: '1081809524013',
    projectId: 'career-quest-a8c11',
    storageBucket: 'career-quest-a8c11.appspot.com',
    androidClientId: '1081809524013-1uihp4rqlb9s92upqog71qot978g5m7m.apps.googleusercontent.com',
    iosClientId: '1081809524013-3t7qbhfi9nroa50fgvkd3ddq8mqajd1k.apps.googleusercontent.com',
    iosBundleId: 'com.akrdev.careerQuest',
  );

}